version: 2

project_name: goldy

before:
  hooks:
    - cd cmd/goldy && go mod tidy

builds:
  - id: goldy
    main: ./cmd/goldy
    binary: goldy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    name_template: "goldy_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: SacredTexts
    name: goldy
