version: 2

project_name: goldy

before:
  hooks:
    - bash -c "cd cmd/goldy && go mod tidy"

builds:
  - id: goldy
    dir: cmd/goldy
    main: .
    binary: goldy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "goldy_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: SacredTexts
    name: goldy
